language: node_js
notifications:
  email: false
node_js:
  - "6"
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE users;'
  - mysql -e 'use users;create table userInfo(id int unsigned auto_increment primary key not null, userName varchar(50),name varchar(50),sex varchar(50),age int,tel varchar(50),email varchar(50),note varchar(50))charset=utf8;'